### PR TITLE
refactor: simplify release step with local env variables

### PR DESCRIPTION
**Pull request by innovaker**
Improves the readability and makes it easier to debug.

### CODE REVIEW

**Comment by innovaker** [comment]
Put on hold until #47 goes through.

**Comment by innovaker** [comment]
Rebased onto #47 and ready for review.

**Comment by innovaker** [comment]
Put on hold until #48 goes through.

**Comment by innovaker** [comment]
Rebased onto #48 and ready for review (again).

**Review by petejohanson — APPROVED** [review]
Reads better to me, definitely.

**Pull request merged**
